---

- block:
    - name: get checksum list
      set_fact:
        __loki_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + loki_version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: get checksum for {{ go_arch }} architecture
      set_fact:
        __loki_checksum: "{{ __loki_checksums | loki_checksum(item, 'linux', go_arch) }}"
  delegate_to: localhost

- name: download {{ item }} binary to local folder
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  get_url:
    url: "{{ loki_release_download_url }}/download/v{{ loki_version }}/{{ item }}-linux-amd64.zip"
    dest: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64.zip"
    checksum: "sha256:{{ __loki_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract {{ item }} archive
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  unarchive:
    src: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64.zip"
    dest: "{{ loki_local_tmp_directory }}/"
    copy: false

- name: detect binary file for {{ item }}
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  stat:
    path: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64"
  register: stat_file_binary

- block:
    - name: propagate loki binaries
      copy:
        src: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64"
        dest: "{{ loki_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ loki_system_user }}"
        group: "{{ loki_system_group }}"
        remote_src: "{{ 'true' if loki_direct_download else 'false' }}"

    - name: make files executable
      file:
        path: "{{ loki_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ loki_system_user }}"
        group: "{{ loki_system_group }}"
  when:
    - stat_file_binary.stat.exists

...
