---

- name: checksum
  become: false
  delegate_to: localhost
  run_once: true
  block:
    - name: get checksum list
      bodsch.scm.github_checksum:
        project: grafana
        repository: loki
        checksum_file: SHA256SUMS
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        architecture: "{{ ansible_architecture }}"
        system: "{{ ansible_facts.system }}"
        version: "v{{ loki_version }}"
      register: _latest_checksum

    - name: define checksum for {{ go_arch }} architecture
      ansible.builtin.set_fact:
        __loki_checksum: "{{ _latest_checksum.checksums | loki_checksum(item, 'linux', go_arch) }}"
      when:
        - _latest_checksum.rc == 0
        - _latest_checksum.checksum is defined
        - _latest_checksum.checksum | string | length > 0

- name: download {{ item }} binary to local folder
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  run_once: "{{ 'false' if loki_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ loki_release_download_url }}/download/v{{ loki_version }}/{{ item }}-linux-amd64.zip"
    dest: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64.zip"
    checksum: "sha256:{{ __loki_checksum }}"
    mode: 0660
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: extract {{ item }} archive
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  run_once: "{{ 'false' if loki_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64.zip"
    dest: "{{ loki_local_tmp_directory }}/"
    copy: false

- name: detect binary file for {{ item }}
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  run_once: "{{ 'false' if loki_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64"
  register: stat_file_binary

- name: copy files
  when:
    - stat_file_binary.stat.exists
  block:
    - name: propagate loki binaries
      ansible.builtin.copy:
        src: "{{ loki_local_tmp_directory }}/{{ item }}-linux-amd64"
        dest: "{{ loki_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ loki_system_user }}"
        group: "{{ loki_system_group }}"
        remote_src: "{{ 'true' if loki_direct_download else 'false' }}"

    - name: make files executable
      ansible.builtin.file:
        path: "{{ loki_install_path }}/{{ item }}"
        mode: 0755
        owner: "{{ loki_system_user }}"
        group: "{{ loki_system_group }}"

...
