---

- name: create link to binary
  ansible.builtin.file:
    src: "{{ loki_install_path }}/{{ item }}"
    dest: /usr/bin/{{ item }}
    state: link
    force: true
  loop: "{{ loki_packages }}"
  loop_control:
    index_var: index
    label: "{{ item }}"
  notify:
    - restart loki

- name: create loki data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
    mode: 0755
  loop:
    - "{{ loki_storage_dir }}"
    - "{{ loki_storage_dir }}/index"
    - "{{ loki_storage_dir }}/chunks"
    - "{{ loki_storage_dir }}/wal"
    - "{{ loki_storage_dir }}/compactor"
    - "{{ loki_storage_dir }}/boltdb-shipper-active"
    - "{{ loki_storage_dir }}/boltdb-shipper-cache"
    - "{{ loki_storage_dir }}/rules"
    - "{{ loki_storage_dir }}/rules-scratch"
    - "{{ loki_storage_dir }}/ruler-wal"

- name: create systemd service unit
  ansible.builtin.template:
    src: "init/systemd/loki.service.j2"
    dest: "{{ systemd_lib_directory }}/loki.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload

- name: create systemd service configuration
  ansible.builtin.template:
    src: "loki.j2"
    dest: "{{ loki_defaults_directory }}/loki"
    force: true
    owner: root
    group: "{{ loki_system_group }}"
    mode: 0640
  notify:
    - restart loki

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/loki.fact
    mode: 0755

...
