---

- include_tasks: prepare.yml

- name: download archives
  include_tasks: download.yml
  loop:
    - loki
    - logcli
  loop_control:
    index_var: index
    label: "{{ item }}"
  when:
    - not stat_loki_binary.stat.exists

- include_tasks: install.yml

- include_tasks: configure.yml

- include_tasks: service.yml
...
