---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: define delegate instance for download handling
  set_fact:
    loki_delegate_to: "{{ ansible_host }}"
    loki_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/loki', true) }}/{{ loki_version }}"
  when:
    - loki_direct_download

- name: install dependency
  package:
    name: "{{ loki_requirements }}"
    state: present
  when:
    - loki_requirements | default([]) | count > 0

- name: gathering facts now
  setup:

- block:
    - name: get latest release
      uri:
        url: "https://api.github.com/repos/grafana/loki/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: set loki version to {{ _latest_release.json.tag_name[1:] }}
      set_fact:
        loki_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - loki_version == "latest"

- name: detect our installation path '{{ loki_install_path | dirname }}'
  stat:
    path: "{{ loki_install_path | dirname }}"
    get_checksum: false
  register: stat_loki_path
  ignore_errors: true

- name: user and group handling
  block:
    - name: create loki group
      group:
        name: "{{ loki_system_group }}"
        state: present
        system: true

    - name: create loki user
      user:
        name: "{{ loki_system_user }}"
        groups: "{{ loki_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
  when:
    - loki_system_user != "root"

- name: flush handlers
  meta: flush_handlers

- name: detect installed loki binary
  stat:
    path: "{{ loki_install_path }}/loki"
  register: stat_loki_binary

- name: create download directory
  become: false
  delegate_to: "{{ loki_delegate_to }}"
  file:
    path: "{{ loki_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  block:
    - name: create loki group
      group:
        name: "{{ loki_system_group }}"
        state: present
        system: true

    - name: create loki user
      user:
        name: "{{ loki_system_user }}"
        groups: "{{ loki_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
  when:
    - loki_system_user != "root"

- name: create install directory
  file:
    path: "{{ loki_install_path }}"
    state: directory
    owner: "{{ loki_system_user }}"
    group: "{{ loki_system_group }}"
    mode: 0755

# - name: fix directory rights for {{ loki_install_path | dirname }}
#   file:
#     path: "{{ loki_install_path | dirname }}"
#     state: directory
#     owner: "{{ loki_system_user }}"
#     group: "{{ loki_system_group }}"
#     mode: 0755
#     recurse: true

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: merge loki configuration between defaults and custom
  set_fact:
    loki_config_chunk_store: "{{ loki_defaults_config_chunk_store | combine( loki_config_chunk_store, recursive=True ) }}"
    loki_config_common: "{{ loki_defaults_config_common | combine( loki_config_common, recursive=True ) }}"
    loki_config_compactor: "{{ loki_defaults_config_compactor | combine( loki_config_compactor, recursive=True ) }}"
    loki_config_distributor: "{{ loki_defaults_config_distributor | combine( loki_config_distributor, recursive=True ) }}"
    loki_config_frontend: "{{ loki_defaults_config_frontend | combine( loki_config_frontend, recursive=True ) }}"
    loki_config_frontend_worker: "{{ loki_defaults_config_frontend_worker | combine( loki_config_frontend_worker, recursive=True ) }}"
    loki_config_index_gateway: "{{ loki_defaults_config_index_gateway | combine( loki_config_index_gateway, recursive=True ) }}"
    loki_config_ingester: "{{ loki_defaults_config_ingester | combine( loki_config_ingester, recursive=True ) }}"
    loki_config_ingester_client: "{{ loki_defaults_config_ingester_client | combine( loki_config_ingester_client, recursive=True ) }}"
    loki_config_limits: "{{ loki_defaults_config_limits | combine( loki_config_limits, recursive=True ) }}"
    loki_config_memberlist: "{{ loki_defaults_config_memberlist | combine( loki_config_memberlist, recursive=True ) }}"
    loki_config_querier: "{{ loki_defaults_config_querier | combine( loki_config_querier, recursive=True ) }}"
    loki_config_query_range: "{{ loki_defaults_config_query_range | combine( loki_config_query_range, recursive=True ) }}"
    loki_config_query_scheduler: "{{ loki_defaults_config_query_scheduler | combine( loki_config_query_scheduler, recursive=True ) }}"
    loki_config_ruler: "{{ loki_defaults_config_ruler | combine( loki_config_ruler, recursive=True ) }}"
    loki_config_runtime: "{{ loki_defaults_config_runtime | combine( loki_config_runtime, recursive=True ) }}"
    loki_config_schema: "{{ loki_defaults_config_schema | combine( loki_config_schema, recursive=True ) }}"
    loki_config_server: "{{ loki_defaults_config_server | combine( loki_config_server, recursive=True ) }}"
    loki_config_storage: "{{ loki_defaults_config_storage | combine( loki_config_storage, recursive=True ) }}"
    loki_config_table_manager: "{{ loki_defaults_config_table_manager | combine( loki_config_table_manager, recursive=True ) }}"
    loki_config_tracing: "{{ loki_defaults_config_tracing | combine( loki_config_tracing, recursive=True ) }}"

...
