---
- name: converge
  hosts: all
  any_errors_fatal: false

  environment:
    NETRC: ''

  roles:
    - role: ansible-loki
      vars:
        loki_version: "2.5.0"

    - role: ansible-loki
      vars:
        loki_version: "2.6.1"

    - role: ansible-loki
      vars:
        loki_version: "2.7.2"
