---

- name: verify config
  become: true
  ansible.builtin.command: |
    loki \
      -verify-config \
      -log.level debug \
      -config.file {{ loki_config_dir }}/loki.yml

- name: restart loki
  become: true
  ansible.builtin.service:
    name: loki
    state: restarted

- name: reload loki
  become: true
  ansible.builtin.service:
    name: loki
    state: reloaded

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

...
