---

- name: verify config
  become: true
  command: |
    loki \
      -verify-config \
      -log.level debug \
      -config.file {{ loki_config_dir }}/loki.yml

- name: restart loki
  become: true
  service:
    name: loki
    state: restarted

- name: reload loki
  become: true
  service:
    name: loki
    state: reloaded

- name: daemon-reload
  become: true
  systemd:
    daemon_reload: true
    force: true

...
