---
name: lint

on:
  pull_request:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 0"

defaults:
  run:
    working-directory: 'ansible-loki'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          # DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: true
          # VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
