---
name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 0"

defaults:
  run:
    working-directory: 'ansible-loki'

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          # DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ANSIBLE: true
          # VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

  arch:
    name: "loki: ${{ matrix.scenario }} - ${{ matrix.image }} / python: ${{ matrix.python-version }}, ansible: ${{ matrix.ansible-version }}"
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
        ansible-version:
          - '4.1'
          - '5.1'
          - '6.1'
        scenario:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  deb:
    name: "loki: ${{ matrix.scenario }} - ${{ matrix.image }} / python: ${{ matrix.python-version }}, ansible: ${{ matrix.ansible-version }}"
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
          - ubuntu:20.04
        ansible-version:
          - '4.1'
          - '5.1'
          - '6.1'
        scenario:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  rpm:
    name: "loki: ${{ matrix.scenario }} - ${{ matrix.image }} / python: ${{ matrix.python-version }}, ansible: ${{ matrix.ansible-version }}"
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - oraclelinux:8
          - rockylinux:8
          - almalinux:8
        ansible-version:
          - '5.1'

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  publish:
    if: github.ref == 'refs/heads/main'
    needs:
      - arch
      - deb
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: main
