---
name: CI

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "code linter"
    branches:
      - main
      - feature/*
      - fix/*
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-loki'

jobs:
  arch:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}, loki: ${{ matrix.scenario }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
        ansible-version:
          - '5.1'
          - '6.1'
        scenario:
          # - "2.3"
          # - "2.4"
          - "2.5"
          - "2.6"
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: 🐍 set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}, loki: ${{ matrix.scenario }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
          - ubuntu:20.04
        ansible-version:
          - '5.1'
          - '6.1'
        scenario:
          # - "2.3"
          # - "2.4"
          - "2.5"
          - "2.6"
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: 🐍 set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  rpm:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - oraclelinux:8
          - rockylinux:8
          - almalinux:8
        ansible-version:
          - '5.1'

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: 🐍 set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
