---
name: with updates

on:
  pull_request:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 2 * * 0"

defaults:
  run:
    working-directory: 'ansible-loki'

jobs:

  deb:
    name: "${{ matrix.image }} / python: ${{ matrix.python-version }}, ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - "5.1"

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-loki'

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name with-updates
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
