---
name: with updates

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CI"
    branches:
      - main
      - feature/*
      - fix/*
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-loki'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - "6.1"
        scenario:
          - "with-updates"

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-loki'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name "${{ matrix.scenario }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
